services:
  qiita:
    container_name: qiita-container
    build: .
    volumes:
      - ./:/app
      - ~/.config/qiita-cli/credentials.json:/root/.config/qiita-cli/credentials.json
    tty: true
    ports:
      - "127.0.0.1:8888:8888"
